# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: "3.6"

volumes:
  keys:

services:
  shell:
    image: hyperledger/sawtooth-all:1.1
    container_name: sawtooth-shell-default
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

  validator-0:
    image: hyperledger/sawtooth-validator:1.1
    container_name: sawtooth-validator-default-0
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - keys:/shared_keys
    working_dir: /root
    command: "bash -c \"\
        sawadm keygen --force && \
        endorser.sh &&
        sawset genesis \
          -k /etc/sawtooth/keys/validator.priv \
          -o config-genesis.batch && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.consensus.algorithm.name=pbft \
          sawtooth.consensus.algorithm.version=0.1 \
          sawtooth.consensus.pbft.members=\\['\\\"'$$(cat /etc/sawtooth/keys/validator.pub)'\\\"','\\\"'$$(cat /etc/sawtooth/keys/validator-1.pub)'\\\"','\\\"'$$(cat /etc/sawtooth/keys/validator-2.pub)'\\\"','\\\"'$$(cat /etc/sawtooth/keys/validator-3.pub)'\\\"'\\] \
          -o config.batch && \
        sawadm genesis \
          config-genesis.batch config.batch && \
        mv /etc/sawtooth/keys/validator-* /shared_keys && \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator \
            --endpoint tcp://validator-0:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --scheduler parallel \
            --maximum-peer-connectivity 4 \
    \""
    stop_signal: SIGKILL

  validator-1:
    image: hyperledger/sawtooth-validator:1.1
    container_name: sawtooth-validator-default-1
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - keys:/shared_keys
    command: "bash -c \"\
        while true; do if [ -e /shared_keys/validator-1.pub ]; then mv /shared_keys/validator-1.priv /etc/sawtooth/keys/validator.priv && mv /shared_keys/validator-1.pub /etc/sawtooth/keys/validator.pub; break; fi; sleep 0.5; done; \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator \
            --endpoint tcp://validator-1:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --peers tcp://validator-0:8800
            --scheduler parallel \
            --maximum-peer-connectivity 4 \
    \""
    stop_signal: SIGKILL
    depends_on:
      - validator-0

  validator-2:
    image: hyperledger/sawtooth-validator:1.1
    container_name: sawtooth-validator-default-2
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - keys:/shared_keys
    command: "bash -c \"\
        while true; do if [ -e /shared_keys/validator-2.pub ]; then mv /shared_keys/validator-2.priv /etc/sawtooth/keys/validator.priv && mv /shared_keys/validator-2.pub /etc/sawtooth/keys/validator.pub; break; fi; sleep 0.5; done; \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator \
            --endpoint tcp://validator-2:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --peers tcp://validator-0:8800,tcp://validator-1:8800
            --scheduler parallel \
            --maximum-peer-connectivity 4 \
    \""
    stop_signal: SIGKILL
    depends_on:
      - validator-1

  validator-3:
    image: hyperledger/sawtooth-validator:1.1
    container_name: sawtooth-validator-default-3
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - keys:/shared_keys
    command: "bash -c \"\
        while true; do if [ -e /shared_keys/validator-3.pub ]; then mv /shared_keys/validator-3.priv /etc/sawtooth/keys/validator.priv && mv /shared_keys/validator-3.pub /etc/sawtooth/keys/validator.pub; break; fi; sleep 0.5; done; \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator \
            --endpoint tcp://validator-3:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --peers tcp://validator-0:8800,tcp://validator-1:8800,tcp://validator-2:8800
            --scheduler parallel \
            --maximum-peer-connectivity 4 \
    \""
    stop_signal: SIGKILL
    depends_on:
      - validator-2

  validator-adhoc:
    image: hyperledger/sawtooth-validator:1.1
    container_name: sawtooth-validator-default-adhoc
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - keys:/shared_keys
    command: "bash -c \"\
        while true; do if [ -e /shared_keys/validator-adhoc.pub ]; then mv /shared_keys/validator-adhoc.priv /etc/sawtooth/keys/validator.priv && mv /shared_keys/validator-adhoc.pub /etc/sawtooth/keys/validator.pub; break; fi; sleep 0.5; done; \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator \
            --endpoint tcp://validator-adhoc:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --peers tcp://validator-0:8800,tcp://validator-1:8800,tcp://validator-2:8800,tcp://validator-3:8800
            --scheduler parallel \
            --maximum-peer-connectivity 4 \
    \""
    stop_signal: SIGKILL

  rest-api-0:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api-default-0
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-0:4004 \
          --bind rest-api-0:8008
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-0

  rest-api-1:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api-default-1
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-1:4004 \
          --bind rest-api-1:8008
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-1

  rest-api-2:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api-default-2
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-2:4004 \
          --bind rest-api-2:8008
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-2

  rest-api-3:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api-default-3
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-3:4004 \
          --bind rest-api-3:8008
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-3

  rest-api-adhoc:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api-default-adhoc
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-adhoc:4004 \
          --bind rest-api-adhoc:8008
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-adhoc

  settings-tp-0:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sawtooth-settings-tp-default-0
    expose:
      - 4004
    command: settings-tp -C tcp://validator-0:4004
    stop_signal: SIGKILL
    depends_on:
      - validator-0

  settings-tp-1:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sawtooth-settings-tp-default-1
    expose:
      - 4004
    command: settings-tp -C tcp://validator-1:4004
    stop_signal: SIGKILL
    depends_on:
      - validator-1

  settings-tp-2:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sawtooth-settings-tp-default-2
    expose:
      - 4004
    command: settings-tp -C tcp://validator-2:4004
    stop_signal: SIGKILL
    depends_on:
      - validator-2

  settings-tp-3:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sawtooth-settings-tp-default-3
    expose:
      - 4004
    command: settings-tp -C tcp://validator-3:4004
    stop_signal: SIGKILL
    depends_on:
      - validator-3

  settings-tp-adhoc:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sawtooth-settings-tp-default-adhoc
    expose:
      - 4004
    command: settings-tp -C tcp://validator-adhoc:4004
    stop_signal: SIGKILL
    depends_on:
      - validator-adhoc

  dummy-tp-0:
    image: dummy-tp:0.1
    container_name: dummy-tp-01-0
    expose:
      - 4004
    command: java -jar dummy-tp.jar tcp://validator-0:4004
    stop_signal: SIGKILL
    depends_on:
      - settings-tp-0

  dummy-tp-1:
    image: dummy-tp:0.1
    container_name: dummy-tp-01-1
    expose:
      - 4004
    command: java -jar dummy-tp.jar tcp://validator-1:4004
    stop_signal: SIGKILL
    depends_on:
      - settings-tp-1

  dummy-tp-2:
    image: dummy-tp:0.1
    container_name: dummy-tp-01-2
    expose:
      - 4004
    command: java -jar dummy-tp.jar tcp://validator-2:4004
    stop_signal: SIGKILL
    depends_on:
      - settings-tp-2

  dummy-tp-3:
    image: dummy-tp:0.1
    container_name: dummy-tp-01-3
    expose:
      - 4004
    command: java -jar dummy-tp.jar tcp://validator-3:4004
    stop_signal: SIGKILL
    depends_on:
      - settings-tp-3

  dummy-tp-adhoc:
    image: dummy-tp:0.1
    container_name: dummy-tp-01-adhoc
    expose:
      - 4004
    command: java -jar dummy-tp.jar tcp://validator-adhoc:4004
    stop_signal: SIGKILL
    depends_on:
      - settings-tp-adhoc

  dummy-transaction-submitter:
    image: dummy-transaction-submitter:0.1
    container_name: dummy-transaction-submitter
    stop_signal: SIGKILL
    command: java -jar docker-trick.jar
    depends_on:
      - dummy-tp-0
      - dummy-tp-1
      - dummy-tp-2
      - dummy-tp-3

  pbft-0:
    image: sawtooth-pbft-engine-local:0.1
    container_name: sawtooth-pbft-engine-local-0
    command: ./pbft-engine --connect tcp://validator-0:5050 -vv
    stop_signal: SIGKILL
    depends_on:
      - validator-0
      - validator-1
      - validator-2
      - validator-3

  pbft-1:
    image: sawtooth-pbft-engine-local:0.1
    container_name: sawtooth-pbft-engine-local-1
    command: ./pbft-engine --connect tcp://validator-1:5050 -vv
    stop_signal: SIGKILL
    depends_on:
      - validator-0
      - validator-1
      - validator-2
      - validator-3

  pbft-2:
    image: sawtooth-pbft-engine-local:0.1
    container_name: sawtooth-pbft-engine-local-2
    command: ./pbft-engine --connect tcp://validator-2:5050 -vv
    stop_signal: SIGKILL
    depends_on:
      - validator-0
      - validator-1
      - validator-2
      - validator-3

  pbft-3:
    image: sawtooth-pbft-engine-local:0.1
    container_name: sawtooth-pbft-engine-local-3
    command: ./pbft-engine --connect tcp://validator-3:5050 -vv
    stop_signal: SIGKILL
    depends_on:
      - validator-0
      - validator-1
      - validator-2
      - validator-3

  pbft-adhoc:
    image: sawtooth-pbft-engine-local:0.1
    container_name: sawtooth-pbft-engine-local-adhoc
    command: ./pbft-engine --connect tcp://validator-adhoc:5050 -vv
    stop_signal: SIGKILL
    depends_on:
      - validator-adhoc

  endorser:
    build:
      context: .
      dockerfile: Dockerfile-endorser
    container_name: endorser
    stop_signal: SIGKILL
    expose:
      - 1337
