# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: "3.6"

services:
  endorser:
    build:
      context: .
      dockerfile: Dockerfile-endorser
    container_name: sawtooth-endorser
    expose:
      - 8080
    command: java -jar endorser.jar
    stop_signal: SIGKILL

  dummy-transaction-submitter:
    build:
      context: .
      dockerfile: Dockerfile-transaction-submitter
    container_name: dummy-transaction-submitter
    stop_signal: SIGKILL
    command: java -jar docker-trick.jar
    depends_on:
      - dummy-tp-0
      - dummy-tp-1
      - dummy-tp-2
      - dummy-tp-3

  validator-0:
    build:
      context: .
      dockerfile: Dockerfile-validator
    container_name: sawtooth-validator-0
    expose:
      - 4004
      - 5050
      - 8800
    command: "bash -c \"\
       sawadm keygen validator-1 && \
       sawadm keygen validator-2 && \
       sawadm keygen validator-3 && \
       sawadm keygen && \
       bash pass-your-key.sh validator validator-1 validator-2 validator-3 && \
       sawset genesis \
       -k /etc/sawtooth/keys/validator.priv \
       -o config-genesis.batch && \
       sawset proposal create \
       -k /etc/sawtooth/keys/validator.priv \
       sawtooth.consensus.algorithm.name=pbft \
       sawtooth.consensus.algorithm.version=0.1 \
       sawtooth.consensus.pbft.members=\\['\\\"'$$(cat /etc/sawtooth/keys/validator.pub)'\\\"','\\\"'$$(cat /etc/sawtooth/keys/validator-1.pub)'\\\"','\\\"'$$(cat /etc/sawtooth/keys/validator-2.pub)'\\\"','\\\"'$$(cat /etc/sawtooth/keys/validator-3.pub)'\\\"'\\] \
       -o config.batch && \
       sawadm genesis \
       config-genesis.batch config.batch && \
       echo $$(cat /etc/sawtooth/keys/validator.pub); \
       sawtooth-validator -vv \
       --endpoint tcp://validator-0:8800 \
       --bind component:tcp://eth0:4004 \
       --bind network:tcp://eth0:8800 \
       --bind consensus:tcp://eth0:5050 \
       --peering static \
       --scheduler parallel \
       --maximum-peer-connectivity 4 \
    \""

    stop_signal: SIGKILL
    depends_on:
      - endorser

  validator-1:
    build:
      context: .
      dockerfile: Dockerfile-validator
    container_name: sawtooth-validator-1
    expose:
      - 4004
      - 5050
      - 8800
    command: >
      bash -c "\
        bash get-key.sh validator-1 validator && \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator -vv \
          --endpoint tcp://validator-1:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
          --peering static \
          --peers tcp://validator-0:8800 \
          --scheduler parallel \
          --maximum-peer-connectivity 4 \
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-0

  validator-2:
    build:
      context: .
      dockerfile: Dockerfile-validator
    container_name: sawtooth-validator-2
    expose:
      - 4004
      - 5050
      - 8800
    command: >
      bash -c "\
        bash get-key.sh validator-2 validator && \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator -vv \
          --endpoint tcp://validator-2:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
          --peering static \
          --peers tcp://validator-0:8800,tcp://validator-1:8800 \
          --scheduler parallel \
          --maximum-peer-connectivity 4 \
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-0

  validator-3:
    build:
      context: .
      dockerfile: Dockerfile-validator
    container_name: sawtooth-validator-3
    expose:
      - 4004
      - 5050
      - 8800
    command: >
      bash -c "\
        bash get-key.sh validator-3 validator && \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator -vv \
          --endpoint tcp://validator-3:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
          --peering static \
          --peers tcp://validator-0:8800,tcp://validator-1:8800,tcp://validator-2:8800 \
          --scheduler parallel \
          --maximum-peer-connectivity 4 \
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-0

  validator-adhoc:
    build:
      context: .
      dockerfile: Dockerfile-validator
    container_name: sawtooth-validator-adhoc
    expose:
      - 4004
      - 5050
      - 8800
    command: >
      bash -c "\
        sawadm keygen validator-adhoc && \
        bash pass-your-key.sh validator-adhoc && \
        mv /etc/sawtooth/keys/validator-adhoc.pub /etc/sawtooth/keys/validator.pub && \
        mv /etc/sawtooth/keys/validator-adhoc.priv /etc/sawtooth/keys/validator.priv && \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator -vv \
          --endpoint tcp://validator-adhoc:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
          --peering static \
          --peers tcp://validator-0:8800,tcp://validator-1:8800,tcp://validator-2:8800,tcp://validator-3:8800 \
          --scheduler parallel \
          --maximum-peer-connectivity 4 \
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-0

  rest-api-0:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api-0
    expose:
      - 8008
      - 4004
    command: >
      bash -c "\
        sawtooth-rest-api \
          --connect tcp://validator-0:4004 \
          --bind rest-api-0:8008 \
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-0

  rest-api-1:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api-1
    expose:
      - 8008
      - 4004
    command: >
      bash -c "\
        sawtooth-rest-api \
          --connect tcp://validator-1:4004 \
          --bind rest-api-1:8008 \
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-1

  rest-api-2:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api-2
    expose:
      - 8008
      - 4004
    command: >
      bash -c "\
        sawtooth-rest-api \
          --connect tcp://validator-2:4004 \
          --bind rest-api-2:8008 \
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-2

  rest-api-3:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api-3
    expose:
      - 8008
      - 4004
    command: >
      bash -c "\
        sawtooth-rest-api \
          --connect tcp://validator-3:4004 \
          --bind rest-api-3:8008 \
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-3

  rest-api-adhoc:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api-adhoc
    expose:
      - 8008
      - 4004
    command: >
      bash -c "\
        sawtooth-rest-api \
          --connect tcp://validator-adhoc:4004 \
          --bind rest-api-adhoc:8008 \
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-adhoc

  settings-tp-0:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sawtooth-settings-tp-0
    expose:
      - 4004
    command: settings-tp -C tcp://validator-0:4004
    stop_signal: SIGKILL
    depends_on:
      - validator-0

  settings-tp-1:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sawtooth-settings-tp-1
    expose:
      - 4004
    command: settings-tp -C tcp://validator-1:4004
    stop_signal: SIGKILL
    depends_on:
      - validator-1

  settings-tp-2:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sawtooth-settings-tp-2
    expose:
      - 4004
    command: settings-tp -C tcp://validator-2:4004
    stop_signal: SIGKILL
    depends_on:
      - validator-2

  settings-tp-3:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sawtooth-settings-tp-3
    expose:
      - 4004
    command: settings-tp -C tcp://validator-3:4004
    stop_signal: SIGKILL
    depends_on:
      - validator-3

  settings-tp-adhoc:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sawtooth-settings-tp-adhoc
    expose:
      - 4004
    command: settings-tp -C tcp://validator-adhoc:4004
    stop_signal: SIGKILL
    depends_on:
      - validator-adhoc

  dummy-tp-0:
    build:
      context: .
      dockerfile: Dockerfile-dummy-tp
    container_name: dummy-tp-01-0
    expose:
      - 4004
    command: java -jar dummy-tp.jar tcp://validator-0:4004
    stop_signal: SIGKILL
    depends_on:
      - settings-tp-0

  dummy-tp-1:
    build:
      context: .
      dockerfile: Dockerfile-dummy-tp
    container_name: dummy-tp-01-1
    expose:
      - 4004
    command: java -jar dummy-tp.jar tcp://validator-1:4004
    stop_signal: SIGKILL
    depends_on:
      - settings-tp-1

  dummy-tp-2:
    build:
      context: .
      dockerfile: Dockerfile-dummy-tp
    container_name: dummy-tp-01-2
    expose:
      - 4004
    command: java -jar dummy-tp.jar tcp://validator-2:4004
    stop_signal: SIGKILL
    depends_on:
      - settings-tp-2

  dummy-tp-3:
    build:
      context: .
      dockerfile: Dockerfile-dummy-tp
    container_name: dummy-tp-01-3
    expose:
      - 4004
    command: java -jar dummy-tp.jar tcp://validator-3:4004
    stop_signal: SIGKILL
    depends_on:
      - settings-tp-3

  dummy-tp-adhoc:
    build:
      context: .
      dockerfile: Dockerfile-dummy-tp
    container_name: dummy-tp-01-adhoc
    expose:
      - 4004
    command: java -jar dummy-tp.jar tcp://validator-adhoc:4004
    stop_signal: SIGKILL
    depends_on:
      - settings-tp-adhoc

  pbft-0:
    build:
      context: .
      dockerfile: Dockerfile-pbft-engine
    expose:
      - 5050
    container_name: sawtooth-pbft-engine-local-0
    command: ./pbft-engine --connect tcp://validator-0:5050 -vv
    stop_signal: SIGKILL
    depends_on:
      - validator-0

  pbft-1:
    build:
      context: .
      dockerfile: Dockerfile-pbft-engine
    expose:
      - 5050
    container_name: sawtooth-pbft-engine-local-1
    command: ./pbft-engine --connect tcp://validator-1:5050 -vv
    stop_signal: SIGKILL
    depends_on:
      - validator-1

  pbft-2:
    build:
      context: .
      dockerfile: Dockerfile-pbft-engine
    expose:
      - 5050
    container_name: sawtooth-pbft-engine-local-2
    command: ./pbft-engine --connect tcp://validator-2:5050 -vv
    stop_signal: SIGKILL
    depends_on:
      - validator-2

  pbft-3:
    build:
      context: .
      dockerfile: Dockerfile-pbft-engine
    expose:
      - 5050
    container_name: sawtooth-pbft-engine-local-3
    command: ./pbft-engine --connect tcp://validator-3:5050 -vv
    stop_signal: SIGKILL
    depends_on:
      - validator-3

  pbft-adhoc:
    build:
      context: .
      dockerfile: Dockerfile-pbft-engine
    expose:
      - 5050
    container_name: sawtooth-pbft-engine-local-adhoc
    command: ./pbft-engine --connect tcp://validator-adhoc:5050 -vv
    stop_signal: SIGKILL
    depends_on:
      - validator-adhoc
