FROM hyperledger/sawtooth-validator:1.1

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

COPY endorser-connector/build/libs/endorser-connector-0.1.jar endorser-connector.jar
COPY create-proposal.sh create-proposal.sh
COPY pass-your-key.sh pass-your-key.sh
COPY get-key.sh get-key.sh
COPY retrieve-keys.sh retrieve-keys.sh
COPY remove-adhoc-keys.sh remove-adhoc-keys.sh